# Generated by Django 3.2.4 on 2021-06-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_participationcontract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participationcontract',
            old_name='contract',
            new_name='contract_id',
        ),
    ]
