# Generated by Django 3.2.4 on 2021-06-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_id_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id_create',
            field=models.IntegerField(),
        ),
    ]
