# Generated by Django 3.2.4 on 2021-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contract_id_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='address',
            field=models.CharField(default='srdvtyb745ei65w4', max_length=255),
            preserve_default=False,
        ),
    ]
