# Generated by Django 3.2.4 on 2021-06-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_rename_contract_participationcontract_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationcontract',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_id_participation', to='contract.contract'),
        ),
    ]
